changelog:
  exclude:
    # リリースノートから除外したいユーザー
    authors:
      - github-actions # <-- 追加
  categories:
    - title: New Features 🎉
      labels:
        - "enhancement"
    - title: Fix Changes 🛠
      labels:
        - "fix"
    - title: Bug Fix 🐛
      labels:
        - "bug"
    - title: Other Changes 📝
      labels:
        - "*"