changelog:
  exclude:
    # リリースノートから除外したいユーザー
    authors:
      - github-actions
    labels:
      - "chore"
  categories:
    - title: New Features 🎉
      labels:
        - "enhancement"
    - title: Fix Changes 🛠
      labels:
        - "fix"
    - title: Bug Fix 🐛
      labels:
        - "bug"
    - title: Other Changes 📝
      labels:
        - "*"
  template: |
    ## Changes in this release 🚀

    $CHANGES
    
