[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sc-system-ai"
version = "0.0.1"
description = "A sample Python project"
readme = "README.md"
dependencies = [
    "python-dotenv",
    "langchain",
    "langchain-community",
    "langchain-openai",
]

[tool.setuptools.packages.find]
where = ["src"]