[tool.poetry]
name = "sc-system-ai"
version = "0.1.0"
description = "Package for handling LLM in sc-system."
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
