from sc_system_ai.agents.tools.magic_function import magic_function
from sc_system_ai.agents.tools.search_duckduckgo import search as search_duckduckgo
from sc_system_ai.agents.tools.search_school_data import search_shool_data