name: Assign Label
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
jobs:
  assign-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler_branch.yml