name: Release workflow [minor]

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    - name: Create new branch for updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout -b release-updates

    - name: Bump version
      run: |
        # Update the version number automatically (minor version bump as an example)
        poetry version minor
        # Stage the version bump
        git add pyproject.toml
        git status
        # Commit the version bump
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git diff
        git commit -m "Bump version to $(poetry version --short)"

    - name: Push changes back to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push -u origin release-updates

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release-updates
        base: main
        title: "Release Updates"
        body: "This PR contains version bump and release updates."
        
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/release-updates'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v$(poetry version --short)
        release_name: Release $(poetry version --short)
        draft: false
        prerelease: false
        body: |
          Release notes for version $(poetry version --short)
